image:
  file: .gitpod.Dockerfile

tasks:
  - before: clear && echo 'Wel...'
    init: echo 'hello'
    command: echo 'welcome'

vscode:
  extensions:
    - redhat.java
    - k--kato.intellij-idea-keybindings
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    
